// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"member/internal/dao/internal"
)

// umsMemberProductCategoryRelationDao is the data access object for the table ums_member_product_category_relation.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberProductCategoryRelationDao struct {
	*internal.UmsMemberProductCategoryRelationDao
}

var (
	// UmsMemberProductCategoryRelation is a globally accessible object for table ums_member_product_category_relation operations.
	UmsMemberProductCategoryRelation = umsMemberProductCategoryRelationDao{internal.NewUmsMemberProductCategoryRelationDao()}
)

// Add your custom methods and functionality below.
