// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"micro-mall.dev/app/member/internal/dao/internal"
)

// umsMemberLevelDao is the data access object for the table ums_member_level.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberLevelDao struct {
	*internal.UmsMemberLevelDao
}

var (
	// UmsMemberLevel is a globally accessible object for table ums_member_level operations.
	UmsMemberLevel = umsMemberLevelDao{internal.NewUmsMemberLevelDao()}
)

// Add your custom methods and functionality below.
