// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"micro-mall.dev/app/member/internal/dao/internal"
)

// umsMemberMemberTagRelationDao is the data access object for the table ums_member_member_tag_relation.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberMemberTagRelationDao struct {
	*internal.UmsMemberMemberTagRelationDao
}

var (
	// UmsMemberMemberTagRelation is a globally accessible object for table ums_member_member_tag_relation operations.
	UmsMemberMemberTagRelation = umsMemberMemberTagRelationDao{internal.NewUmsMemberMemberTagRelationDao()}
)

// Add your custom methods and functionality below.
