// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"micro-mall.dev/app/member/internal/dao/internal"
)

// umsMemberRuleSettingDao is the data access object for the table ums_member_rule_setting.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberRuleSettingDao struct {
	*internal.UmsMemberRuleSettingDao
}

var (
	// UmsMemberRuleSetting is a globally accessible object for table ums_member_rule_setting operations.
	UmsMemberRuleSetting = umsMemberRuleSettingDao{internal.NewUmsMemberRuleSettingDao()}
)

// Add your custom methods and functionality below.
