// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"micro-mall.dev/app/member/internal/dao/internal"
)

// umsMemberStatisticsInfoDao is the data access object for the table ums_member_statistics_info.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberStatisticsInfoDao struct {
	*internal.UmsMemberStatisticsInfoDao
}

var (
	// UmsMemberStatisticsInfo is a globally accessible object for table ums_member_statistics_info operations.
	UmsMemberStatisticsInfo = umsMemberStatisticsInfoDao{internal.NewUmsMemberStatisticsInfoDao()}
)

// Add your custom methods and functionality below.
