// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"micro-mall.dev/app/member/internal/dao/internal"
)

// umsMemberDao is the data access object for the table ums_member.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberDao struct {
	*internal.UmsMemberDao
}

var (
	// UmsMember is a globally accessible object for table ums_member operations.
	UmsMember = umsMemberDao{internal.NewUmsMemberDao()}
)

// Add your custom methods and functionality below.
