// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"member/internal/dao/internal"
)

// umsMemberLoginLogDao is the data access object for the table ums_member_login_log.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberLoginLogDao struct {
	*internal.UmsMemberLoginLogDao
}

var (
	// UmsMemberLoginLog is a globally accessible object for table ums_member_login_log operations.
	UmsMemberLoginLog = umsMemberLoginLogDao{internal.NewUmsMemberLoginLogDao()}
)

// Add your custom methods and functionality below.
