// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"member/internal/dao/internal"
)

// umsMemberReceiveAddressDao is the data access object for the table ums_member_receive_address.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberReceiveAddressDao struct {
	*internal.UmsMemberReceiveAddressDao
}

var (
	// UmsMemberReceiveAddress is a globally accessible object for table ums_member_receive_address operations.
	UmsMemberReceiveAddress = umsMemberReceiveAddressDao{internal.NewUmsMemberReceiveAddressDao()}
)

// Add your custom methods and functionality below.
