// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"member/internal/dao/internal"
)

// umsMemberTaskDao is the data access object for the table ums_member_task.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberTaskDao struct {
	*internal.UmsMemberTaskDao
}

var (
	// UmsMemberTask is a globally accessible object for table ums_member_task operations.
	UmsMemberTask = umsMemberTaskDao{internal.NewUmsMemberTaskDao()}
)

// Add your custom methods and functionality below.
