// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"member/internal/dao/internal"
)

// umsMemberTagDao is the data access object for the table ums_member_tag.
// You can define custom methods on it to extend its functionality as needed.
type umsMemberTagDao struct {
	*internal.UmsMemberTagDao
}

var (
	// UmsMemberTag is a globally accessible object for table ums_member_tag operations.
	UmsMemberTag = umsMemberTagDao{internal.NewUmsMemberTagDao()}
)

// Add your custom methods and functionality below.
