
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:ChangeMe_Root_123!@tcp(nps.nobugs.net.cn:30306)/micro-mall-member"
        descriptionTag: true
    pbentity:
      - link: "mysql:root:ChangeMe_Root_123!@tcp(nps.nobugs.net.cn:30306)/micro-mall-member"
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app