apiVersion: v1
kind: Service
metadata:
  name: proxima-etcd-client
  namespace: proxima-etcd
  labels:
    app: proxima-etcd
spec:
  type: NodePort
  selector:
    app: proxima-etcd
  ports:
    - name: client
      port: 2379
      targetPort: client
      nodePort: 32379
