apiVersion: v1
kind: Service
metadata:
  name: micro-mall-etcd-client
  namespace: micro-mall-etcd
  labels:
    app: micro-mall-etcd
spec:
  type: NodePort
  selector:
    app: micro-mall-etcd
  ports:
    - name: client
      port: 2379
      targetPort: client
      nodePort: 32379
