apiVersion: v1
kind: Service
metadata:
  name: micro-mall-etcd-headless
  namespace: micro-mall-etcd
  labels:
    app: micro-mall-etcd
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: micro-mall-etcd
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
